---
# file: roles/aptupdate/tasks/01_proxy.yml

 - name: copy  10proxy
   become: yes
   become_method: sudo
   template:
     src=10proxy.j2
     dest=/etc/apt/apt.conf.d/10proxy
     owner=root
     mode=644
