---
# file: roles/osmaster/tasks/main.yml

 - name: copy  local.conf
   become: yes
   become_method: sudo
   copy:
     src=local.conf
     dest=/opt/stack/devstack
     owner=stack
     mode=644

 - name: chage _IP_ to defined master's IP
   become: yes
   become_method: sudo
   replace:
     dest=/opt/stack/devstack/local.conf
     regexp='_IP_$'
     replace='{{ master }}'

 - name: run stack.sh
   become: yes
   become_user: stack
   command: /opt/stack/devstack/stack.sh
   args:
     chdir: /opt/stack/devstack
   register: command_result
   failed_when: "'Error' in command_result.stderr"

